apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: portfolio-pvc
spec:
  accessModes:
      - ReadWriteOnce
  resources:
      requests:
          storage: 1Gi
  storageClassName: local-storage
  selector:
    matchLabels:
        app: portfolio-database
    matchExpressions:
      - key: type
        operator: In
        values:
          - local
          - database
          - keycloak
