apiVersion: v1
kind: PersistentVolume
metadata:
  name: portfolio-pv
spec:
  capacity:
      storage: 1Gi
  accessModes:
      - ReadWriteOnce # ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Retain # Retain, Recycle, Delete
  volumeMode: Filesystem # Filesystem, Block
  storageClassName: local-storage # slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/data
    server: 172.17.0.2
