apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
        - name: busybox
          image: registry.k8s.io/busybox
          command:
            - /bin/sh
          args:
            - -c
            -  sleep 60; touch /tmp/healthy; sleep 600
          ports:
            - containerPort: 3000
          startupProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 3 # Número de segundos após o início do container para o liveness
            periodSeconds: 10 # Intervalo de tempo entre as verificações
            failureThreshold: 3 # Número de falhas pra considerar a aplicação não saudável
            successThreshold: 1 # Número de sucessos para zerar o failureThreshold (No liveness é 1)
            timeoutSeconds: 3 # Timeout da chamada
            terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
