apiVersion: apps/v1       # API version for ReplicaSet (using 'apps/v1' for this type of object)
kind: ReplicaSet          # Kind of Kubernetes object, which is a ReplicaSet
metadata:
  name: myreplicaset      # Name of the ReplicaSet
spec:
  replicas: 10             # Number of Pod replicas to maintain
  selector:               # Selector to match the labels of Pods that this ReplicaSet manages
    matchLabels:
      app: web            # Pods with this label will be managed by this ReplicaSet
  template:               # Template defines the Pod that will be created by the ReplicaSet
    metadata:
      labels:             # Labels applied to the Pods created by this template
        app: web          # Labels the Pod with 'app: web'
    spec:
      containers:         # List of containers for the Pod (this one has a single container)
        - name: web       # Name of the container
          image: kubedevio/web-color:green          # Image used for the container (version 'blue')
          ports:
            - containerPort: 80                    # Exposes port 80 in the container
              name: http                           # Port named 'http'
              protocol: TCP                        # Using TCP protocol for communication
