apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
        cpu: 500m
      defaultRequest:
        memory: 256Mi
        cpu: 250m
      max:
        memory: 1Gi
        cpu: "1"
      min:
        memory: 128Mi
        cpu: 100m
      maxLimitRequestRatio:
        memory: "2"
        cpu: "4"
