apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulador-do-caos
spec:
  replicas: 10
  selector:
    matchLabels:
      app: simulador-do-caos
  template:
    metadata:
      labels:
        app: simulador-do-caos
    spec:
      containers:
        - name: simulador-do-caos
          image: kubedevio/simulador-do-caos:v1
          ports:
            - containerPort: 3000
          resources:
            # Define resource requests and limits for the container, when the limits and requests are the same,
            # the container is given a guaranteed amount of that resource, and can burst up to the limit., the QOS class is Guaranteed.
            limits:
              cpu: "0.5"  # 50% of 1 CPU
              memory: "512Mi" # 512 Mb
            requests:
              cpu: "0.5" # 25% of 1 CPU
              memory: "512Mi" # 256 Mb
---
apiVersion: v1
kind: Service
metadata:
  name: simulador-do-caos
spec:
  selector:
    app: simulador-do-caos
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
